version: "3"

services:
  jenkins:
    build:
      context: .
    hostname: jenkins
    container_name: jenkins
    restart: unless-stopped

    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./Data/jobs:/var/jenkins_home/jobs
      - ./Data/users:/var/jenkins_home/users
      - ./Data/userContent:/var/jenkins_home/userContent

   
    environment:
      - TZ=Europe/Copenhagen
      # - JENKINS_SLAVE_AGENT_PORT=50000
      # - JENKINS_OPTS=
      # - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
